name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ secrets.APP_ENV }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      SUPERUSER_USERNAME: ${{ secrets.SUPERUSER_USERNAME }}
      SUPERUSER_EMAIL: ${{ secrets.SUPERUSER_EMAIL }}
      SUPERUSER_PASSWORD: ${{ secrets.SUPERUSER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Prepare database
        run: uv run bash app/scripts/prestart.sh

      - name: Run tests
        run: uv run pytest
